In [1]:
import numpy as np

In [3]:
A = np.array([1.2, -0.5, -1.5, 1.7]).reshape((2,2))
print(A)

[[ 1.2 -0.5]
 [-1.5  1.7]]


In [5]:
W, V = np.linalg.eig(A)
print(W)
print(V)

[0.54861218 2.35138782]
[[-0.60889368  0.3983218 ]
 [-0.79325185 -0.91724574]]


In [14]:
V_inv = np.linalg.inv(V)
print(V_inv)
W_dig = np.diag(W)
print(W_dig)

[[-1.04891063 -0.45549841]
 [ 0.90711819 -0.69629656]]
[[0.54861218 0.        ]
 [0.         2.35138782]]


In [15]:
V@W_dig@V_inv

array([[ 1.2, -0.5],
       [-1.5,  1.7]])

In [18]:
V.dot(W_dig).dot(V_inv)

array([[ 1.2, -0.5],
       [-1.5,  1.7]])

In [19]:
np.matmul(V, np.matmul(W_dig, V_inv))

array([[ 1.2, -0.5],
       [-1.5,  1.7]])