In [1]:
import numpy as np

## 고유값분해

### 고유값 분해의 기본

In [2]:
A = np.array([1.2, -0.5, -1.5, 1.7]).reshape((2,2))
print(A)

[[ 1.2 -0.5]
 [-1.5  1.7]]


In [3]:
W, V = np.linalg.eig(A)
print(W)
print(V)

[0.54861218 2.35138782]
[[-0.60889368  0.3983218 ]
 [-0.79325185 -0.91724574]]


In [4]:
V_inv = np.linalg.inv(V)
print(V_inv)
W_dig = np.diag(W)
print(W_dig)

[[-1.04891063 -0.45549841]
 [ 0.90711819 -0.69629656]]
[[0.54861218 0.        ]
 [0.         2.35138782]]


In [5]:
V@W_dig@V_inv

array([[ 1.2, -0.5],
       [-1.5,  1.7]])

In [6]:
V.dot(W_dig).dot(V_inv)

array([[ 1.2, -0.5],
       [-1.5,  1.7]])

In [7]:
np.matmul(V, np.matmul(W_dig, V_inv))

array([[ 1.2, -0.5],
       [-1.5,  1.7]])

### 회전변환의 고유값분해

In [8]:
from rotation_matrix import RoationMatrix

In [11]:
rot = RoationMatrix()
theta = np.deg2rad(30)
rot2d_theta = rot.rot2D(theta)
print(rot2d_theta)

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]


In [12]:
W, V = np.linalg.eig(rot2d_theta)
print(W)
print(V)

[0.8660254+0.5j 0.8660254-0.5j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
